version: '3.3'
services:
    thapmu:
        build: .
        container_name: thapmu
        restart: always
        ports:
            - 1883:1883/tcp
            - 3000:3000/tcp
        volumes:
            - $PWD:/usr/src/app
