version: '3.3'
services:
  mqtt:
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/config
    image: eclipse-mosquitto:latest

  db:
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=db_user
      - DOCKER_INFLUXDB_INIT_PASSWORD=db_pwd_123
      - DOCKER_INFLUXDB_INIT_ORG=thapmu
      - DOCKER_INFLUXDB_INIT_BUCKET=thapmu
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    image: influxdb:latest

  grafana:
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    image: grafana/grafana:latest

  thapmu:
    container_name: thapmu
    restart: unless-stopped
    environment:
      - INFLUXDB_ORG=thapmu
      - INFLUXDB_BUCKET=thapmu
      - INFLUXDB_TOKEN=my-super-secret-auth-token
    depends_on:
      - mqtt
      - db
    image: ghcr.io/kgeri201/thapmu:main

volumes:
  grafana_data: {}
